CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"));
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE UNIQUE INDEX "auth_group_permissions_group_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id"), "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "username" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "home_homepage" ("page_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "wagtailcore_page" ("id"));
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE TABLE "taggit_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE);
CREATE TABLE "taggit_taggeditem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" integer NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "tag_id" integer NOT NULL REFERENCES "taggit_tag" ("id"));
CREATE INDEX "taggit_taggeditem_af31437c" ON "taggit_taggeditem" ("object_id");
CREATE INDEX "taggit_taggeditem_417f1b1c" ON "taggit_taggeditem" ("content_type_id");
CREATE INDEX "taggit_taggeditem_76f094bc" ON "taggit_taggeditem" ("tag_id");
CREATE INDEX "taggit_taggeditem_content_type_id_196cc965_idx" ON "taggit_taggeditem" ("content_type_id", "object_id");
CREATE TABLE "wagtailcore_grouppagepermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id"), "permission_type" varchar(20) NOT NULL);
CREATE UNIQUE INDEX "wagtailcore_grouppagepermission_group_id_0898bdf8_uniq" ON "wagtailcore_grouppagepermission" ("group_id", "page_id", "permission_type");
CREATE INDEX "wagtailcore_grouppagepermission_0e939a4f" ON "wagtailcore_grouppagepermission" ("group_id");
CREATE INDEX "wagtailcore_grouppagepermission_1a63c800" ON "wagtailcore_grouppagepermission" ("page_id");
CREATE TABLE "wagtailcore_pageviewrestriction" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id"), "password" varchar(255) NOT NULL);
CREATE INDEX "wagtailcore_pageviewrestriction_1a63c800" ON "wagtailcore_pageviewrestriction" ("page_id");
CREATE TABLE "wagtailcore_site" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "hostname" varchar(255) NOT NULL, "port" integer NOT NULL, "is_default_site" bool NOT NULL, "root_page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id"), "site_name" varchar(255) NULL);
CREATE UNIQUE INDEX "wagtailcore_site_hostname_2c626d70_uniq" ON "wagtailcore_site" ("hostname", "port");
CREATE INDEX "wagtailcore_site_0897acf4" ON "wagtailcore_site" ("hostname");
CREATE INDEX "wagtailcore_site_8372b497" ON "wagtailcore_site" ("root_page_id");
CREATE TABLE "wagtailcore_pagerevision" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "submitted_for_moderation" bool NOT NULL, "created_at" datetime NOT NULL, "content_json" text NOT NULL, "approved_go_live_at" datetime NULL, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id"), "user_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE INDEX "wagtailcore_pagerevision_7ac06fbb" ON "wagtailcore_pagerevision" ("submitted_for_moderation");
CREATE INDEX "wagtailcore_pagerevision_1a63c800" ON "wagtailcore_pagerevision" ("page_id");
CREATE INDEX "wagtailcore_pagerevision_e8701ad4" ON "wagtailcore_pagerevision" ("user_id");
CREATE TABLE "wagtailcore_collection" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "path" varchar(255) NOT NULL UNIQUE, "depth" integer unsigned NOT NULL, "numchild" integer unsigned NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE "wagtailcore_groupcollectionpermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE UNIQUE INDEX "wagtailcore_groupcollectionpermission_group_id_a21cefe9_uniq" ON "wagtailcore_groupcollectionpermission" ("group_id", "collection_id", "permission_id");
CREATE INDEX "wagtailcore_groupcollectionpermission_0a1a4dd8" ON "wagtailcore_groupcollectionpermission" ("collection_id");
CREATE INDEX "wagtailcore_groupcollectionpermission_0e939a4f" ON "wagtailcore_groupcollectionpermission" ("group_id");
CREATE INDEX "wagtailcore_groupcollectionpermission_8373b171" ON "wagtailcore_groupcollectionpermission" ("permission_id");
CREATE TABLE "wagtailcore_page" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "path" varchar(255) NOT NULL UNIQUE, "depth" integer unsigned NOT NULL, "numchild" integer unsigned NOT NULL, "title" varchar(255) NOT NULL, "live" bool NOT NULL, "has_unpublished_changes" bool NOT NULL, "url_path" text NOT NULL, "seo_title" varchar(255) NOT NULL, "show_in_menus" bool NOT NULL, "search_description" text NOT NULL, "go_live_at" datetime NULL, "expire_at" datetime NULL, "expired" bool NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "owner_id" integer NULL REFERENCES "auth_user" ("id"), "locked" bool NOT NULL, "latest_revision_created_at" datetime NULL, "first_published_at" datetime NULL, "slug" varchar(255) NOT NULL);
CREATE INDEX "wagtailcore_page_417f1b1c" ON "wagtailcore_page" ("content_type_id");
CREATE INDEX "wagtailcore_page_5e7b1936" ON "wagtailcore_page" ("owner_id");
CREATE INDEX "wagtailcore_page_8c754174" ON "wagtailcore_page" ("first_published_at");
CREATE INDEX "wagtailcore_page_2dbcba41" ON "wagtailcore_page" ("slug");
CREATE TABLE "wagtaildocs_document" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "file" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id"), "uploaded_by_user_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE INDEX "wagtaildocs_document_0a1a4dd8" ON "wagtaildocs_document" ("collection_id");
CREATE INDEX "wagtaildocs_document_ef01e2b6" ON "wagtaildocs_document" ("uploaded_by_user_id");
CREATE TABLE "wagtailembeds_embed" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "url" varchar(200) NOT NULL, "max_width" smallint NULL, "type" varchar(10) NOT NULL, "html" text NOT NULL, "title" text NOT NULL, "author_name" text NOT NULL, "provider_name" text NOT NULL, "thumbnail_url" varchar(200) NULL, "width" integer NULL, "height" integer NULL, "last_updated" datetime NOT NULL);
CREATE UNIQUE INDEX "wagtailembeds_embed_url_8a2922d8_uniq" ON "wagtailembeds_embed" ("url", "max_width");
CREATE TABLE "wagtailforms_formsubmission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "form_data" text NOT NULL, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id"), "submit_time" datetime NOT NULL);
CREATE INDEX "wagtailforms_formsubmission_1a63c800" ON "wagtailforms_formsubmission" ("page_id");
CREATE TABLE "wagtailimages_filter" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "spec" varchar(255) NOT NULL UNIQUE);
CREATE TABLE "wagtailimages_image" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "file" varchar(100) NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "created_at" datetime NOT NULL, "focal_point_x" integer unsigned NULL, "focal_point_y" integer unsigned NULL, "focal_point_width" integer unsigned NULL, "focal_point_height" integer unsigned NULL, "uploaded_by_user_id" integer NULL REFERENCES "auth_user" ("id"), "file_size" integer unsigned NULL, "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id"));
CREATE INDEX "wagtailimages_image_fde81f11" ON "wagtailimages_image" ("created_at");
CREATE INDEX "wagtailimages_image_ef01e2b6" ON "wagtailimages_image" ("uploaded_by_user_id");
CREATE INDEX "wagtailimages_image_0a1a4dd8" ON "wagtailimages_image" ("collection_id");
CREATE TABLE "wagtailimages_rendition" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "width" integer NOT NULL, "height" integer NOT NULL, "focal_point_key" varchar(255) NOT NULL, "filter_id" integer NOT NULL REFERENCES "wagtailimages_filter" ("id"), "image_id" integer NOT NULL REFERENCES "wagtailimages_image" ("id"), "file" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "wagtailimages_rendition_image_id_03110280_uniq" ON "wagtailimages_rendition" ("image_id", "filter_id", "focal_point_key");
CREATE INDEX "wagtailimages_rendition_0a317463" ON "wagtailimages_rendition" ("filter_id");
CREATE INDEX "wagtailimages_rendition_f33175e6" ON "wagtailimages_rendition" ("image_id");
CREATE TABLE "wagtailredirects_redirect" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "old_path" varchar(255) NOT NULL, "is_permanent" bool NOT NULL, "redirect_link" varchar(200) NOT NULL, "redirect_page_id" integer NULL REFERENCES "wagtailcore_page" ("id"), "site_id" integer NULL REFERENCES "wagtailcore_site" ("id"));
CREATE UNIQUE INDEX "wagtailredirects_redirect_old_path_783622d7_uniq" ON "wagtailredirects_redirect" ("old_path", "site_id");
CREATE INDEX "wagtailredirects_redirect_91a0b591" ON "wagtailredirects_redirect" ("old_path");
CREATE INDEX "wagtailredirects_redirect_2fd79f37" ON "wagtailredirects_redirect" ("redirect_page_id");
CREATE INDEX "wagtailredirects_redirect_9365d6e7" ON "wagtailredirects_redirect" ("site_id");
CREATE TABLE "wagtailsearch_query" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "query_string" varchar(255) NOT NULL UNIQUE);
CREATE TABLE "wagtailsearch_querydailyhits" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "hits" integer NOT NULL, "query_id" integer NOT NULL REFERENCES "wagtailsearch_query" ("id"));
CREATE UNIQUE INDEX "wagtailsearch_querydailyhits_query_id_1dd232e6_uniq" ON "wagtailsearch_querydailyhits" ("query_id", "date");
CREATE INDEX "wagtailsearch_querydailyhits_0bbeda9c" ON "wagtailsearch_querydailyhits" ("query_id");
CREATE TABLE "wagtailsearch_editorspick" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sort_order" integer NULL, "description" text NOT NULL, "query_id" integer NOT NULL REFERENCES "wagtailsearch_query" ("id"), "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id"));
CREATE INDEX "wagtailsearch_editorspick_0bbeda9c" ON "wagtailsearch_editorspick" ("query_id");
CREATE INDEX "wagtailsearch_editorspick_1a63c800" ON "wagtailsearch_editorspick" ("page_id");
CREATE TABLE "wagtailusers_userprofile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "approved_notifications" bool NOT NULL, "rejected_notifications" bool NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id"), "submitted_notifications" bool NOT NULL);
